# Generated by Django 2.2.16 on 2020-10-13 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('verify_signature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='Current_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
