# Generated by Django 2.2.16 on 2020-10-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify_signature', '0002_auto_20201013_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='Image_Path',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
