# Generated by Django 2.2.16 on 2020-10-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify_signature', '0003_auto_20201013_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slip',
            name='Account_Holder_Name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='slip',
            name='Bank_Name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
